version: '3.8'

services:
  ai-engine:
    build:
      context: ./ai-engine
      args:
        PIP_EXTRA_INDEX_URL: https://pypi.org/simple
    environment:
      PIP_EXTRA_INDEX_URL: https://pypi.org/simple
    volumes:
      - ./ai-engine:/app

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
