version: '3.8'

services:
  ai-engine:
    build: ./ai-engine
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=
    volumes:
      - ./ai-engine:/app

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - SUPABASE_URL=https://oythrmgqykvycsmvrlvv.supabase.co
      - SUPABASE_KEY=
      - AI_ENGINE_URL=http://ai-engine:5000
    depends_on:
      - ai-engine

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

networks:
  default:
    driver: bridge
